import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/home/Sidebar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "API Build CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body
        className={`${poppins.className}   bg-white min-h-screen dark:bg-dark text-black dark:text-white antialiased `}
      >
        <section className=" flex">
          <section className=" w-[20%]">
            <Sidebar />
          </section>
          <section className=" w-[80%] ">{children}</section>
        </section>
      </body>
    </html>
  );
}
