import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/home/Sidebar";
import PrivateComponentWrapper from "@/components/wrappers/PrivateComponentWrapper";
import BodyWrapper from "@/components/wrappers/BodyWrapper";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "API Build CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body
        className={`${poppins.className}   bg-white min-h-screen dark:bg-dark text-black dark:text-white antialiased `}
      >
        <section className=" flex">
          <PrivateComponentWrapper className=" w-[20%]">
            <Sidebar />
          </PrivateComponentWrapper>
          <BodyWrapper>{children}</BodyWrapper>
        </section>
        <Toaster />
      </body>
    </html>
  );
}
